send_keys:
  description: send keys.
  fields:
    me:
      description: 设备me值
      example: '0010'
    agt:
      description: 智慧中心agt
      example: '_xXXXXXXXXXXXXXXXXX'
    ai:
      description: 遥控器AI
      example: 'AI_IR_xxxx_xxxxxxxx'
    category:
      description: 遥控设备类别
      example: 'custom'
    brand:
      description: 遥控器品牌
      example: 'custom'
    keys:
      description: 遥控器命令key
      example: '["key"]'
